### ISSUE TITLE
some panels only shown when Klipper is connected

### ISSUE THREAD

**Issue by SmoothieAq** [cadriel/fluidd#214]
In 1.11.2, the "Software Updates" and "Job History" panels are only shown when Klipper is connected.
I usually only am connected when printing and power to the mcu is controlled by the Moonraker power plugin.

In 1.10 I had software updates in the menu even if not connected. 

In 1.11.2 I don't have "Job History" when not connected, but I do have "Printer Stats".

**Comment by cadriel** [comment]
This is fixed for the next release.

**Comment by SmoothieAq** [comment]
"Software updates" are now available, but "Job history" is still not available when not connected.

**Comment by SmoothieAq** [comment]
@cadriel, I don't know how to reopen the issues...
